name: Generate Snake Animation
on:
  schedule:
    - cron: "0 0 * * *"  # Atualiza todo dia à meia-noite (UTC)
  workflow_dispatch:     # Permite executar manualmente

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: Rossatto20  # Substitua se for outro usuário
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output       # Cria uma branch chamada "output"
          build_dir: dist             # Pasta onde a imagem é salva
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token automático do GitHub
